version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: css-loader
    versions:
    - ">= 4.2.a"
    - "< 4.3"
