version: 2.1

commands:
  setup_npm:
    description: "Set up NPM dependencies"
    steps:
      - restore_cache:
          keys:
            - dependency-cache-2-{{ checksum "package-lock.json" }}
            - dependency-cache-2-
      - run:
          name: Dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-2-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

jobs:
  build:
    docker:
      - image: cimg/node:12.18.3
    steps:
      - checkout
      - setup_npm
      - run:
          name: Build
          command: npm run build-production
      - run:
          name: Check Bundle Size
          command: npm run bundlewatch

  test:
    docker:
      - image: cimg/node:12.18.3
    steps:
      - checkout
      - setup_npm
      - run:
          name: Lint Code
          command: npm run lint
      - run:
          name: Test
          command: npm test

  publish_docker:
    machine: true
    steps:
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: |
          docker build -t envirodgi/ui:$CIRCLE_SHA1 .
          docker build -t envirodgi/ui:latest .
      - run: |
          docker push envirodgi/ui:$CIRCLE_SHA1
          docker push envirodgi/ui:latest

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: release
      - test:
          filters:
            branches:
              ignore: release

  build-and-publish:
    jobs:
      - build:
          filters:
            branches:
              only:
                - release
      - publish_docker:
          requires:
            - build
