version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-2-{{ checksum "package-lock.json" }}
      - run:
          name: Dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-2-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run linter
          command: npm run lint
      - run:
          name: Test
          command: npm test

  publish_docker:
    machine: true
    steps:
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: |
          docker build -t envirodgi/ui:$CIRCLE_SHA1 .
          docker build -t envirodgi/ui:latest .
      - run: |
          docker push envirodgi/ui:$CIRCLE_SHA1
          docker push envirodgi/ui:latest

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: release

  build-and-publish:
    jobs:
      - build:
          filters:
            branches:
              only:
                - release
      - publish_docker:
          requires:
            - build
